"""Clean up and tidy the Markdown that NVIDIA's ``.html.md`` mirror returns.

The mirror is generated by a Jina-Reader-style proxy that prepends a small
header block (``Title:``/``URL Source:``/``Markdown Content:``) and appends
a ``Links/Buttons:`` enumeration of every link on the page. Inside the body,
Sphinx headings keep an ``[#](... "Link to this heading")`` anchor stub, code
fences are followed by a stray ``Copy to clipboard`` line, and on some pages
every heading collapses to a setext underline regardless of nesting depth
which destroys the section hierarchy.

The functions here are individually tested-by-eye on the CUDA Programming
Guide and meant to be applied as a pipeline by ``clean_mirror_body``.
"""

from __future__ import annotations

import re
from urllib.parse import urljoin, urlparse

_HEADER_LINE_RE = re.compile(
    r"^(?P<key>Title|URL Source|Published Time|Warning|Markdown Content):"
    r"\s*(?P<val>.*)$"
)
_TITLE_TRAILER_RE = re.compile(r"\s+[—–\-]\s+[A-Za-z0-9].*$")


def _normalise_title(value: str) -> str:
    value = value.strip()
    value = _TITLE_TRAILER_RE.sub("", value)
    value = value.rstrip("#").rstrip()
    return value


def strip_reader_wrapper(md: str) -> tuple[str, str]:
    """Strip the Jina-Reader-style preamble and trailing links list.

    Returns ``(body, title)`` where ``title`` is the extracted ``Title:``
    value (already stripped of the trailing ``— Site Name`` and ``#`` noise),
    or an empty string if the page didn't have one.
    """

    lines = md.splitlines()
    title = ""

    i = 0
    while i < len(lines) and not lines[i].strip():
        i += 1
    while i < len(lines):
        line = lines[i]
        if not line.strip():
            i += 1
            continue
        m = _HEADER_LINE_RE.match(line)
        if m is None:
            break
        if m.group("key") == "Title" and not title:
            title = _normalise_title(m.group("val"))
        i += 1
    body = "\n".join(lines[i:])

    body = re.sub(
        r"\n+Links/Buttons:\s*\n(?:[ \t]*-[^\n]*\n?)*\s*\Z",
        "\n",
        body,
    )

    return body.strip("\n") + "\n", title


_LINK_RE = re.compile(
    r"""
    (?P<bang>!?)            # optional image marker
    \[(?P<label>[^\]]*)\]   # [label]
    \(
        \s*
        (?P<target><[^>]+>|[^()\s]+)   # URL or <URL>
        (?:\s+"(?P<title>[^"]*)")?     # optional "title"
        \s*
    \)
    """,
    re.VERBOSE,
)


def _absolutize(target: str, base_url: str) -> str:
    target = target.strip()
    if target.startswith("<") and target.endswith(">"):
        inner = _absolutize(target[1:-1], base_url)
        return f"<{inner}>"
    if not target:
        return target
    if target.startswith("#"):
        return target
    if target.startswith(("http://", "https://", "data:", "mailto:", "tel:", "javascript:")):
        return target
    if target.startswith("//"):
        scheme = urlparse(base_url).scheme or "https"
        return f"{scheme}:{target}"
    return urljoin(base_url, target)


def absolutize_links(md: str, page_url: str) -> str:
    """Resolve every ``](...)`` link and image target against ``page_url``.

    Critical for image URLs in particular — most pages reference
    ``../_images/foo.png`` which is unusable once the file is read in
    isolation. Anchors (``#section``) are deliberately left as-is because
    they point inside the same stitched document.
    """

    def repl(m: re.Match[str]) -> str:
        bang = m.group("bang")
        label = m.group("label")
        target = _absolutize(m.group("target"), page_url)
        title = m.group("title")
        if title is not None:
            return f'{bang}[{label}]({target} "{title}")'
        return f"{bang}[{label}]({target})"

    return _LINK_RE.sub(repl, md)


_HEADING_ANCHOR_RE = re.compile(
    r'[ \t]*\[[^\]]*\]\([^)]*?"(?:Link|Permalink) to this [a-z]+"\)[ \t]*'
)


def strip_heading_anchors(md: str) -> str:
    """Remove the Sphinx anchor stubs that decorate every heading/figure.

    Several label shapes appear across NVIDIA's mirror corpus, all tagged
    by a distinctive ``"Link to this <word>"`` / ``"Permalink to this
    <word>"`` title:

    * ``[#](url "Link to this heading")`` and ``[\\#](...)`` — CUDA
      Programming Guide and other pydata-sphinx-theme sites.
    * ``[](url "Permalink to this headline")`` /
      ``[](url "Permalink to this image")`` — RTD-themed sites with non-
      empty mirrors (older mirror generation).
    * ``[\uf0c1](url "Permalink to this headline")`` — RTD-themed sites
      whose mirror inlines Font Awesome's chain glyph (U+F0C1) as the
      anchor label (Nsight Compute, etc.).

    All of these are pure navigation chrome — match on the title pattern
    and accept any label.
    """

    return _HEADING_ANCHOR_RE.sub("", md)


_SECTION_NUM_RE = re.compile(r"^\s*([0-9]+(?:\.[0-9]+)*)\.\s")
_SETEXT_RE = re.compile(r"^([^\n]+)\n([=-]{3,})[ \t]*$", re.MULTILINE)


def _heading_depth_for(text: str, underline_char: str) -> int:
    m = _SECTION_NUM_RE.match(text)
    if m:
        parts = m.group(1).split(".")
        return max(1, min(6, len(parts) - 1 or 1))
    return 1 if underline_char == "=" else 2


def setext_to_atx(md: str) -> str:
    """Convert ``Heading\\n====`` / ``Heading\\n----`` to ``# Heading`` form.

    On some pages the mirror flattens every heading to a setext ``---``
    underline regardless of nesting depth, which collapses the entire section
    hierarchy. Re-derive the depth from the leading ``N.M.K.`` section
    number when present so the document keeps a usable outline.
    """

    def _repl(m: re.Match[str]) -> str:
        text = m.group(1).rstrip()
        underline = m.group(2)[0]
        if not text.strip():
            return m.group(0)
        depth = _heading_depth_for(text, underline)
        return f"{'#' * depth} {text.strip()}"

    return _SETEXT_RE.sub(_repl, md)


_COPY_TO_CLIPBOARD_RE = re.compile(r"^[ \t]*Copy to clipboard[ \t]*$\n?", re.MULTILINE)
_BLANK_RUN_RE = re.compile(r"\n{3,}")
_HEADING_TRAILING_HASH_RE = re.compile(
    r"^(?P<hashes>#{1,6}[ \t]+.+?)[ \t]*\\?#[ \t]*$",
    re.MULTILINE,
)
_FAKE_HEADING_RE = re.compile(
    r"^(?P<hashes>#{1,6})[ \t]+(?P<rest>(?![A-Z0-9]).+)$",
    re.MULTILINE,
)


def strip_ui_residue(md: str) -> str:
    md = _COPY_TO_CLIPBOARD_RE.sub("", md)
    md = _HEADING_TRAILING_HASH_RE.sub(lambda m: m.group("hashes").rstrip(), md)
    md = _FAKE_HEADING_RE.sub(
        lambda m: f"\\{m.group('hashes')} {m.group('rest')}",
        md,
    )
    md = _BLANK_RUN_RE.sub("\n\n", md)
    return md


_LEADING_H1_RE = re.compile(r"^#\s+\S")


def ensure_h1(body: str, title: str) -> str:
    """Prepend ``# <title>`` to the body if it doesn't already lead with one.

    Many pages put the chapter title only in the ``Title:`` line of the
    mirror wrapper; once that wrapper is stripped the chapter heading is
    gone entirely. We only inspect the first non-empty line — chapter
    titles always come first, and looking deeper risks false positives like
    shell comments (``# generate PTX``) inside code blocks whose fences the
    mirror sometimes drops.
    """

    if not title:
        return body
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if _LEADING_H1_RE.match(stripped):
            return body
        break
    return f"# {title}\n\n{body.lstrip()}"


def is_broken_paragraph_page(body: str) -> bool:
    """Detect pages where the markdown mirror collapsed everything into one
    giant paragraph (zero structure left).

    These pages are the small minority where ``.html.md`` is unusable; the
    pipeline falls back to fetching the regular HTML and converting it
    locally.
    """

    if len(body) < 4_000:
        return False
    return body.count("\n") < 10


def clean_mirror_body(body: str, *, title: str, page_url: str) -> str:
    """Apply every cleanup pass that should happen on a mirror body.

    The order matters: anchor stubs must go before ``setext_to_atx`` so the
    underline detection isn't fooled by the trailing brackets, and link
    absolutisation must happen last so we don't accidentally rewrite a
    URL we just synthesised in ``ensure_h1``.
    """

    body = strip_heading_anchors(body)
    body = setext_to_atx(body)
    body = strip_ui_residue(body)
    body = ensure_h1(body, title)
    body = absolutize_links(body, page_url)
    return body
