name: Build and Install

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-install:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.2.0-devel-ubuntu22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Wheel
        run: |
          python -m pip install --upgrade build
          python -m build --sdist
      - name: Install Wheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install --verbose dist/*.tar.gz
