name: Build and Install

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        id: setup_python
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Build Wheel
        run: |
          python -m pip install --upgrade build
          python -m build --sdist
      - name: Install Wheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install --verbose dist/*.tar.gz
